name: Linux

on:
  pull_request:
    branches:
      - testing
  push:
    branches: 
      - dev

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Linux-${{ matrix.kind }}
        cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - name: Build
        run: |
          xmake
      - name: Package
        run: |
          cd build/linux/x86_64/release/ && zip -r xavine-linux.zip * && mv xavine-linux.zip ../../../../
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            xavine-linux.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          generateReleaseNotes: true
          tag: test
#          tag: ${{ github.event.pull_request.title }}
          omitBodyDuringUpdate: true
          prerelease: true
          replacesArtifacts: true